projects:
  - name: Settings - API KEY
    id: 6227a2e6da6f5200e76ec9c2
  - name: Documentation asset
    id: 623b3ac9459a5d00df324533
  - name: Billable metrics - Create a billable metric
    id: 623b42fddc2f2c017440cb5b
  - name: Plans - Create a plan
    id: 62442e1098bdeb0134fd179b
  - name: All - Give more context in creation flows
    id: 624d9ad91a1c4d0149998c5b
  - name: Customers - Customers list and details
    id: 624ef2f26583e200fe08b6fd
  - name: All - Edit & delete ≠ objects
    id: 6256de3622fcba00d9830a1e
  - name: Customers - Edit & delete a customer
    id: 626162c105cb2c00e673c696
  - name: Customer - Add invoice data to customer creation and edition
    id: 626c0c056054aa00f9967401
  - name: 'Billable metrics - Add Sum, Max, Count unique aggregation type'
    id: 62694d8eb0d327016e05c5b5
  - name: Settings - Webhooks in app
    id: 6271200612648800e9bdfd47
  - name: Setting - Set tax rates in application
    id: 62728ff2d06c9b00f4ea46ad
  - name: Plans - Add Graduated in charge model
    id: 62793bb8e62e1200cbcdddf8
  - name: Plans - Add Package per unit in charge model
    id: 62820857abe2eb0109dfb546
  - name: 'Coupons - Create, edit coupons'
    id: 62865490ae25a500b104b108
  - name: Logs - Log usage & measurement
    id: 628cf7593d43eb010ec6b067
  - name: Coupons - Apply coupons to customers
    id: 628b8c5f8161d800e7c1c562
  - name: Add-ons - Apply an Add-on to a Customer
    id: 6295e54aa233f00167720fe8
  - name: 'Add-ons - Create, Edit, Delete an Add-on'
    id: 62972835d3981000e8b0eb9d
  - name: Plans - Add Percentage in charge model
    id: 62a0b709894be901198aeddb
  - name: Plans - Bill Charges monthly on a yearly plan
    id: 62a30bc3940c3583b1a429be
  - name: Lago <> Stripe connection + impact on customer view
    id: 62b1edda611dee64a01ad185
  - name: Plans - Add weekly interval to Plans
    id: 62b32ec020fff7fdc7426158
  - name: All - Empty and error state in app
    id: 62bac374775f2a0472421630
  - name: Onboarding - Create & Connect to an account
    id: 620bc4d45f16c800e2324b82
  - name: Settings - Invoice settings
    id: 62ab2cff6d409cff712298ea
  - name: Logs - Log current usage
    id: 62c3f3f85ba98dad7106f33b
  - name: "\U0001F44D [Ready for dev] - Navigation - Display app version"
    id: 62c6c95d9333c1ac1be9f938
  - name: 'Plans,Customers - Add multiple plans to a customer'
    id: 62d7f6138ca07e88551c9dde
  - name: '⚙️ [WIP] - General - FE environment infos'
    id: 62f50d2512182c6df6c39e37
  - name: "\U0001F44D [Ready for dev] - Add Percentage in charge model"
    id: 62ff5cfec490a4767eccdf6e
  - name: '⚙️ [WIP] - Customers - Subscription on anniversary date'
    id: 62ea7cd19883fb6718fa823c
  - name: "\U0001F44D [Ready for dev] - Plans - Add Volume in charge model"
    id: 6304e74718860633c15905f2
format: flat
variants: true
