sources:
  components:
    enabled: true
  projects:
    - name: Settings - API KEY
      id: 6227a2e6da6f5200e76ec9c2
      fileName: Settings - API KEY
    - name: Documentation asset
      id: 623b3ac9459a5d00df324533
      fileName: Documentation asset
    - name: Billable metrics - Create a billable metric
      id: 623b42fddc2f2c017440cb5b
      fileName: Billable metrics - Create a billable metric
    - name: Plans - Create a plan
      id: 62442e1098bdeb0134fd179b
      fileName: Plans - Create a plan
    - name: All - Give more context in creation flows
      id: 624d9ad91a1c4d0149998c5b
      fileName: All - Give more context in creation flows
    - name: Customers - Customers list and details
      id: 624ef2f26583e200fe08b6fd
      fileName: Customers - Customers list and details
    - name: All - Edit & delete ‚â† objects
      id: 6256de3622fcba00d9830a1e
      fileName: All - Edit & delete ‚â† objects
    - name: Customers - Edit & delete a customer
      id: 626162c105cb2c00e673c696
      fileName: Customers - Edit & delete a customer
    - name: Customer - Add invoice data to customer creation and edition
      id: 626c0c056054aa00f9967401
      fileName: Customer - Add invoice data to customer creation and edition
    - name: Billable metrics - Add Sum, Max, Count unique aggregation type
      id: 62694d8eb0d327016e05c5b5
      fileName: Billable metrics - Add Sum, Max, Count unique aggregation type
    - name: Settings - Webhooks in app
      id: 6271200612648800e9bdfd47
      fileName: Settings - Webhooks in app
    - name: Setting - Set tax rates in application
      id: 62728ff2d06c9b00f4ea46ad
      fileName: Setting - Set tax rates in application
    - name: Plans - Add Graduated in charge model
      id: 62793bb8e62e1200cbcdddf8
      fileName: Plans - Add Graduated in charge model
    - name: Plans - Add Package per unit in charge model
      id: 62820857abe2eb0109dfb546
      fileName: Plans - Add Package per unit in charge model
    - name: Coupons - Create, edit coupons
      id: 62865490ae25a500b104b108
      fileName: Coupons - Create, edit coupons
    - name: Logs - Log usage & measurement
      id: 628cf7593d43eb010ec6b067
      fileName: Logs - Log usage & measurement
    - name: Coupons - Apply coupons to customers
      id: 628b8c5f8161d800e7c1c562
      fileName: Coupons - Apply coupons to customers
    - name: Add-ons - Apply an Add-on to a Customer
      id: 6295e54aa233f00167720fe8
      fileName: Add-ons - Apply an Add-on to a Customer
    - name: Add-ons - Create, Edit, Delete an Add-on
      id: 62972835d3981000e8b0eb9d
      fileName: Add-ons - Create, Edit, Delete an Add-on
    - name: Plans - Add Percentage in charge model
      id: 62a0b709894be901198aeddb
      fileName: Plans - Add Percentage in charge model
    - name: Plans - Bill Charges monthly on a yearly plan
      id: 62a30bc3940c3583b1a429be
      fileName: Plans - Bill Charges monthly on a yearly plan
    - name: Lago <> Stripe connection + impact on customer view
      id: 62b1edda611dee64a01ad185
      fileName: Lago <> Stripe connection + impact on customer view
    - name: Plans - Add weekly interval to Plans
      id: 62b32ec020fff7fdc7426158
      fileName: Plans - Add weekly interval to Plans
    - name: All - Empty and error state in app
      id: 62bac374775f2a0472421630
      fileName: All - Empty and error state in app
    - name: Onboarding - Create & Connect to an account
      id: 620bc4d45f16c800e2324b82
      fileName: Onboarding - Create & Connect to an account
    - name: Settings - Invoice settings
      id: 62ab2cff6d409cff712298ea
      fileName: Settings - Invoice settings
    - name: Logs - Log current usage
      id: 62c3f3f85ba98dad7106f33b
      fileName: Logs - Log current usage
    - name: üëç [Ready for dev] - Navigation - Display app version
      id: 62c6c95d9333c1ac1be9f938
      fileName: üëç [Ready for dev] - Navigation - Display app version
    - name: Plans,Customers - Add multiple plans to a customer
      id: 62d7f6138ca07e88551c9dde
      fileName: Plans,Customers - Add multiple plans to a customer
    - name: ‚öôÔ∏è [WIP] - General - FE environment infos
      id: 62f50d2512182c6df6c39e37
      fileName: ‚öôÔ∏è [WIP] - General - FE environment infos
    - name: üëç [Ready for dev] - Add Percentage in charge model
      id: 62ff5cfec490a4767eccdf6e
      fileName: üëç [Ready for dev] - Add Percentage in charge model
    - name: ‚öôÔ∏è [WIP] - Customers - Subscription on anniversary date
      id: 62ea7cd19883fb6718fa823c
      fileName: ‚öôÔ∏è [WIP] - Customers - Subscription on anniversary date
    - name: üëç [Ready for dev] - Plans - Add Volume in charge model
      id: 6304e74718860633c15905f2
      fileName: üëç [Ready for dev] - Plans - Add Volume in charge model
    - name: ‚öôÔ∏è [WIP] - Credits - Create prepaid credits
      id: 62d175018d4659c9a3eec929
      fileName: ‚öôÔ∏è [WIP] - Credits - Create prepaid credits
    - name: üëç [Ready for dev] - Onboarding - Invite member to organisation
      id: 63208b60a9b2a4c6186bbd26
      fileName: üëç [Ready for dev] - Onboarding - Invite member to organisation
    - name: ‚öôÔ∏è [WIP] - Customers - Overwrite subscription per customer
      id: 6328e70891e49d4d9732180d
      fileName: ‚öôÔ∏è [WIP] - Customers - Overwrite subscription per customer
    - name: ‚öôÔ∏è [WIP] - Customers - Customer hold currency
      id: 632b49dccdbed9536c8497ab
      fileName: ‚öôÔ∏è [WIP] - Customers - Customer hold currency
    - name: üëç [Ready for dev] - Coupons - Create % and recurring coupons
      id: 632d6831010fafe9382b616d
      fileName: üëç [Ready for dev] - Coupons - Create % and recurring coupons
    - name: üëç [Ready for dev] - All - Replace success screen by success toast
      id: 633336529ca3243d15ac9df4
      fileName: üëç [Ready for dev] - All - Replace success screen by success toast
    - name: Customer - Subscription on past - future date
      id: 6335e508a4f742dfb05f54fd
      fileName: Customer - Subscription on past - future date
    - name: üëç [Ready for dev] - Customers - Invoice detail page
      id: 634687058efb4a10996fdbdc
      fileName: üëç [Ready for dev] - Customers - Invoice detail page
    - name: ‚öôÔ∏è [WIP] - B.Metrics and Plans - Dimension
      id: 633b622919283cdbfb2f7233
      fileName: ‚öôÔ∏è [WIP] - B.Metrics and Plans - Dimension
    - name: üëç [Ready for dev] - Settings - Customers - Lago gocardless connection
      id: 634ea0e94c99df2bb59820d9
      fileName: üëç [Ready for dev] - Settings - Customers - Lago gocardless connection
    - name: üëç [Ready for dev] - Coupons - Apply several coupons to customer
      id: 637b4d9f764dcb190431ad4d
      fileName: üëç [Ready for dev] - Coupons - Apply several coupons to customer
    - name: üëç [Ready for dev] - Customers - Invoice grace period
      id: 637f813a9ec65c29fc3ceef3
      fileName: üëç [Ready for dev] - Customers - Invoice grace period
    - name: >-
        üëç [Ready for dev] - Coupons - Option to apply several times the same
        coupon
      id: 638f4825992c44e4381e7a1f
      fileName: >-
        üëç [Ready for dev] - Coupons - Option to apply several times the same
        coupon
    - name: >-
        üëç [Ready for dev] - Credit note - Create and apply credit note to a
        customer
      id: 636bdeec2ea28ae182faa50e
      fileName: >-
        üëç [Ready for dev] - Credit note - Create and apply credit note to a
        customer
    - name: >-
        üëç [Ready for dev] - Settings Customers - Lago x Data Warehouse
        connection
      id: 639c334bcee914d26afecf69
      fileName: >-
        üëç [Ready for dev] - Settings Customers - Lago x Data Warehouse
        connection
    - name: üëç [Ready for dev] - All - Custom ‚â† timezones
      id: 638906e129a144b0c4c27c83
      fileName: üëç [Ready for dev] - All - Custom ‚â† timezones
    - name: Amount placeholder
      id: 639710434b2a96dba29b9140
      fileName: Amount placeholder
    - name: Copy to clipboard
      id: 63a5ba118e83e2c695c6f7c6
      fileName: Copy to clipboard
    - name: üëç [Ready for dev] - Customer - Improve tax and grace period on customer
      id: 63aa085ae8d6be2e0e0ee38b
      fileName: üëç [Ready for dev] - Customer - Improve tax and grace period on customer
    - name: üëç [Ready for dev] - All - License key
      id: 63b315558a78f7b5a6551de7
      fileName: üëç [Ready for dev] - All - License key
    - name: üëç [Ready for dev] - Invoices- Invoice list
      id: 63ac86d51bd1437a2a21f1f9
      fileName: üëç [Ready for dev] - Invoices- Invoice list
    - name: ‚öôÔ∏è [WIP] - All - Search bar in app
      id: 63ba9ee502cfb90849074f4b
      fileName: ‚öôÔ∏è [WIP] - All - Search bar in app
    - name: >-
        ‚öôÔ∏è [WIP] - Coupons - Set frequency forever and limited to a specific
        plan
      id: 63c83a31e697e8e9236da751
      fileName: >-
        ‚öôÔ∏è [WIP] - Coupons - Set frequency forever and limited to a specific
        plan
    - name: ‚öôÔ∏è [WIP] - All - Delete objects linked to subscription
      id: 63cfe207f9f4c2ea8dcf3aa7
      fileName: ‚öôÔ∏è [WIP] - All - Delete objects linked to subscription
    - name: >-
        ‚öôÔ∏è [WIP] - Plan - Warn user if duplicate charge in plan creation and
        edition
      id: 63e254ea592347d77dd3cf03
      fileName: >-
        ‚öôÔ∏è [WIP] - Plan - Warn user if duplicate charge in plan creation and
        edition
    - name: üëç [Ready for dev] - Settings Customers - Lago x Osso connection
      id: 63e26d71cc5ddde09d90bd99
      fileName: üëç [Ready for dev] - Settings Customers - Lago x Osso connection
    - name: üëç [Ready for dev] - Customer Invoice - Update invoice.payment_status
      id: 63eba8199c936977d8e98991
      fileName: üëç [Ready for dev] - Customer Invoice - Update invoice.payment_status
    - name: ‚öôÔ∏è [WIP] - Settings - Define preferred doc language generation
      id: 63e51e8467659a55d188a68c
      fileName: ‚öôÔ∏è [WIP] - Settings - Define preferred doc language generation
    - name: ‚öôÔ∏è [WIP] - Settings - Webhook debugger
      id: 63e27c4800ff170963670e71
      fileName: ‚öôÔ∏è [WIP] - Settings - Webhook debugger
    - name: ‚öôÔ∏è [WIP] - Customers - Metadata on customer & invoice
      id: 63fcc31ebb3fb91189619496
      fileName: ‚öôÔ∏è [WIP] - Customers - Metadata on customer & invoice
    - name: ‚öôÔ∏è [WIP] - Customer - Customer portal
      id: 6419c64c72d2468f025ea25d
      fileName: ‚öôÔ∏è [WIP] - Customer - Customer portal
    - name: ‚öôÔ∏è [WIP] - Settings - Email invoices to final customers
      id: 640766f4ff20c7dac058261b
      fileName: ‚öôÔ∏è [WIP] - Settings - Email invoices to final customers
    - name: Plan-Invoice - Instant charge
      id: 63ff7985343a362251c12744
      fileName: Plan-Invoice - Instant charge
    - name: Subscription drawer - external id input
      id: 642a94e4409e3692d27eda4c
      fileName: Subscription drawer - external id input
    - name: üëç [Ready for dev] - Login - Reset password
      id: 642707b04540bee48d54de86
      fileName: üëç [Ready for dev] - Login - Reset password
    - name: üëç [Ready for dev] - Plans - Create a plan UI refacto
      id: 642d5eac2dc55f7f81e01dd4
      fileName: üëç [Ready for dev] - Plans - Create a plan UI refacto
    - name: ‚öôÔ∏è [WIP] - Coupons - Coupon limited to a billable metric
      id: 643526532896c737f8b18e8f
      fileName: ‚öôÔ∏è [WIP] - Coupons - Coupon limited to a billable metric
    - name: üëç [Ready for dev] - Plans - Set a minimum spending on charges
      id: 643e59213ea23c04674eba8c
      fileName: üëç [Ready for dev] - Plans - Set a minimum spending on charges
    - name: >-
        üëç [Ready for dev] - Coupons - Coupon amount based on total excluding
        tax
      id: 644b9f169e8c4336fd0ad060
      fileName: >-
        üëç [Ready for dev] - Coupons - Coupon amount based on total excluding
        tax
    - name: ‚öôÔ∏è [WIP] - Customer - Create an one off invoice (ex-applied_add-on)
      id: 64538190cd7aa251ac87781b
      fileName: ‚öôÔ∏è [WIP] - Customer - Create an one off invoice (ex-applied_add-on)
    - name: ‚öôÔ∏è [WIP] - Settings - Create tax rate object & apply on org & cus
      id: 645bb18f29c95e96f9cd43e9
      fileName: ‚öôÔ∏è [WIP] - Settings - Create tax rate object & apply on org & cus
    - name: ‚öôÔ∏è [WIP] - Plan - Charges paid in-advance
      id: 646e2d05cf47b79ad4b5ccf5
      fileName: ‚öôÔ∏è [WIP] - Plan - Charges paid in-advance
    - name: ‚öôÔ∏è [WIP] - Settings / Customers - Lago x Adyen Connection
      id: 645d070fa825baf410cec70c
      fileName: ‚öôÔ∏è [WIP] - Settings / Customers - Lago x Adyen Connection
    - name: ‚öôÔ∏è [WIP] - Customer - Add tax_number on customer
      id: 648053ecf72671011f9365ff
      fileName: ‚öôÔ∏è [WIP] - Customer - Add tax_number on customer
    - name: Subscription at drawer fix
      id: 648b171fcdcc85696b5d1cd4
      fileName: Subscription at drawer fix
    - name: Add missing keys
      id: 64999d7a720a1412d1a72cf6
      fileName: Add missing keys
    - name: üëç [Ready for dev] - Settings / Customers - Lago x Stripe SDD
      id: 64aeb7b7d5628db33254c4bb
      fileName: üëç [Ready for dev] - Settings / Customers - Lago x Stripe SDD
    - name: üëç [Ready for dev] - Plans - Add tax to plans
      id: 64be91077c9f2900a38f3ad3
      fileName: üëç [Ready for dev] - Plans - Add tax to plans
    - name: üëç [Ready for dev] - Webhook - Select webhooks signature
      id: 64d23a7dbab3e178ad302aa0
      fileName: üëç [Ready for dev] - Webhook - Select webhooks signature
    - name: üëç [Ready for dev] - Settings - Net payment term
      id: 64c7a896197f1907cbc6371c
      fileName: üëç [Ready for dev] - Settings - Net payment term
    - name: üëç [Ready for dev] - Add-on - Add tax to add-ons & one off invoice
      id: 64d40b7c611d58bb88ec7d63
format: flat
variants: true
