# This Docker Compose file is to use for CI purposes only
# At Lago we use it to run ours integrations tests

version: '3.8'

services:
  db:
    image: postgres:14.0-alpine
    container_name: lago-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lago
      POSTGRES_USER: lago
      POSTGRES_PASSWORD: lago
    ports:
      - 5432:5432
    
  redis:
    image: redis:6.2-alpine
    container_name: lago_redis
    restart: unless-stopped
    ports:
      - 6379:6379
  
  api:
    image: getlago/api:ci
    container_name: lago-api
    restart: unless-stopped
    depends_on: 
      - "db"
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://lago:lago@db:5432/lago
      REDIS_URL: redis://redis:6379
      LAGO_FRONT_URL: http://front
      SECRET_KEY_BASE: secret-key
      LAGO_RSA_PRIVATE_KEY: ${LAGO_RSA_PRIVATE_KEY}
      LAGO_DISABLE_SEGMENT: "true"
      RAILS_LOG_TO_STDOUT: "true"
      LAGO_LICENSE: ${LAGO_LICENSE}
  
  license:
    image: getlago/license:ci
    container_name: lago_license
    restart: unless-stopped
    depends_on: 
      - "db"
    environment:
      - DATABASE_URL=postgres://lago:lago@db:5432/lago

  front:
    image: getlago/front:ci
    container_name: lago-front
    restart: unless-stopped
    environment:
      API_URL: http://api:3000
      NODE_ENV: staging
    ports:
      - 80:80
